[package]
name = "ilos_guidance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32"
csv = "1.1"

[profile.test] 
opt-level = 3
